# author: elliot-huffman
name: release
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: none
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test
      - name: Publish to npm
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}